### ISSUE TITLE
Multiple Lines on a Line Graph?

### ISSUE THREAD

**Issue by vicc** [kevinzhow/PNChart#12]
It would be awesome if there could be an option for more than 1 line on a line graph! This would really make this project amazing!

Same with bar charts!

![sample](https://f.cloud.github.com/assets/1724674/1669626/f3c21db8-5c7d-11e3-8d8d-590d42e9344e.png)

**Comment by bigbadleroybrown** [comment]
Had this been implemented for bar charts as well?

**Comment by tolarewaju3** [comment]
i would like to see this implemented for a bar chart too
