### ISSUE TITLE
PNCircleChart initWithFrame: options

### ISSUE THREAD

**Issue by dredful** [kevinzhow/PNChart#137]
Hi Kevin,

Your chart project is awesome! When implementing the PNCircleChart, I needed some options to control how it displayed. I did so by creating some alternate initWithFrame: methods to account for:

- show/hide UICountingLabel
- providing a shadowColor
- providing a specified line width

I could commit my changes for you to review if others may find these options helpful too.

Thanks,

dredful

**Comment by dredful** [comment]
There is also a small change to allow the Circle to use the full amount of the specified frame.

**Comment by kevinzhow** [comment]
thanks~ please push you pr I will review it 😄

**Comment by dredful** [comment]
Heya Kevin,

My pr is up on GitHub for you.

Thanks again,

Craig

On Thu, Jan 1, 2015 at 10:03 PM, Kevin <notifications@github.com> wrote:

> thanks~ please push you pr I will review it [image: 😄]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinzhow/PNChart/issues/137#issuecomment-68509080>.
>



-- 

   [image: --]

Craig McLeod
[image: http://]about.me/dredful
   <http://about.me/dredful?promo=email_sig>
