### ISSUE TITLE
Crash when using updateChartData: and adding a graph.

### ISSUE THREAD

**Issue by klauslanza** [kevinzhow/PNChart#139]
I thought that updateChartData: would work for updating the chart regardless of initial state and final state (for example when source data changes, even the number of lines), but it only work in limited cases.

Changing to less graphs, for example from 2 lines to 1 line, it's ok. But it's crashing when you add a graph, for example from 2 to 3.

Tested on the
- (IBAction)changeValue:(id)sender
method of demo.

Is it supposed to work even when changing graphs like this or is this a bug?

**Comment by kevinzhow** [comment]
this is a limitation for now, I may update it in next version
