### ISSUE TITLE
PNChart for OS X

### ISSUE THREAD

**Issue by tracy-e** [kevinzhow/PNChart#140]
Hi, I have a version of PNChart compatible with OS X [there](https://github.com/tracy-e/PNChart-OSX), Would you like to set up a branch for OS X so that I can push my version here?

**Comment by kevinzhow** [comment]
Cool

**Comment by kevinzhow** [comment]
You can create a new target in develop branch.

**Comment by tracy-e** [comment]
Actually, my version only works on OS X, If a version compatible with iOS and OS X at the same time, the code will full of `#if` `#else` `#endif` , I think it's not good to maintain for not every contributor are familiar with the two platform.

**Comment by kevinzhow** [comment]
Thats what a good develop should do, just learn more.

**Comment by tracy-e** [comment]
Ok, I will do as you said.
