### ISSUE TITLE
Line chart: option to remove padding at the origin

### ISSUE THREAD

**Issue by asprega** [kevinzhow/PNChart#142]
I could not seem to find a way to remove the padding at the origin of line charts. It would be a nice addition to be able to tune that, up to potentially remove it altogether.

This is the setup of my chart:

```swift
self.lineChart.backgroundColor = UIColor.clearColor()
self.lineChart.showCoordinateAxis = true
self.lineChart.xLabels = ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"]
self.lineChart.yLabelFormat = "$%1.f"
```

and this is how I insert each dataSet:

```swift
let chartLine1Data: [CGFloat] = [200, 250, 550, 580, 630, 600, 750, 700, 680, 700, 820, 1080]
let chartLine1 = PNLineChartData()
chartLine1.itemCount = UInt(chartLine1Data.count)
chartLine1.lineWidth = 2.5
chartLine1.getData = { index in
    return PNLineChartDataItem(y: chartLine1Data[Int(index)])
}
...
self.lineChart.chartData = [chartLine1, ... ] 
```

This is the result:

![schermata 2015-01-12 alle 13 45 42](https://cloud.githubusercontent.com/assets/2210656/5703040/54ec190a-9a61-11e4-8f5b-a19c6911357c.png)

I tried fiddling with the `chartCavanHeight` and `chartCavanWidth` (assuming cavan is "canvas"), along with the number of Y labels but I could not achieve a decent result. Am I missing something or there's no way of eliminating the padding at the origin?

**Comment by kevinzhow** [comment]
padding needs to be modified in source code.

**Comment by asprega** [comment]
@kevinzhow I'm sorry, are you suggesting to manually hack the library source code? Since I imagine this might be interesting for other library users as well, is it possible for you to consider adding this functionality properly (e.g. with a configurable property)? If you are willing to include this functionality I can do a pull request.

Of course hacking the library for me is not a solution, as I don't want to maintain a fork of my own.
