### ISSUE TITLE
Bar Chart: Animate in sequence

### ISSUE THREAD

**Issue by DaveAdams88** [kevinzhow/PNChart#143]
Hi there,

I am using PNBarChart for months of the year

At the moment all the bars animate at the same time... is there a way I can get them to animate in order?

e.g. jan animates to value, then feb, then marc etc

Ideally it would start animating the next bar a few milliseconds before it ends

Tried doing it myself but a little out of my depth!

Loving PNChart!

Thanks,
Dave

**Comment by kevinzhow** [comment]
Yes but little bit complicated
For a quick trick, you can modified the method at here https://github.com/kevinzhow/PNChart/blob/master/PNChart/PNBarChart.m#L246

just add the animation a delay time.
