### ISSUE TITLE
Solved! yValueMax is an int, should be a float

### ISSUE THREAD

**Issue by hamesetawa** [kevinzhow/PNChart#150]
The graph is crashing my app, I'm guessing the array having small doubles affects it.

```
NSArray *mut =
  @[@0, @0, @0, @0, @0, @0.01, @0.703, @0.703];
    [chart setYValues:mut];
```

I get an exception at PNBar setGrade on line 3:
```
[progressline addLineToPoint:CGPointMake(self.frame.size.width / 2.0, (1 - grade) * self.frame.size.height)];
```

For some reason (deduced by many nslogs), grade is equal to inf. 
That makes (1 - grade) * self.frame.size.height equal to -inf.
Which is obviously not a valid point...
Where is grade set? Why is it turning into infinity??

The error I get is:
Assertion failed: (CGFloatIsValid(x) && CGFloatIsValid(y)), function void CGPathAddLineToPoint(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat), file Paths/CGPath.cc, line 265.

EDIT:
I solved it!
I went to PNBarChart, updateBar.
In //height of bar, I changed it to this
```
float grade;
        if (value == 0 || _yValueMax == 0)
        {
            grade = 0;
        }
        else
        {
            grade = (float)value / (float)_yValueMax;
        }
```

And for getYValueMax in PNBarChart
```
- (void)getYValueMax:(NSArray *)yLabels
{
    //float max = [[yLabels valueForKeyPath:@"@max.floatValue"] floatValue];
    float max = -MAXFLOAT;
    for (NSNumber *num in yLabels) {
        float x = num.floatValue;
        if (x > max) max = x;
    }
    _yValueMax = max;
    if (_yValueMax == 0) {
        _yValueMax = _yMinValue;
    }
}
```

And for the real solution... 
I changed yValueMax in PNBarChart.h from int to double.

**Comment by Rnorback** [comment]
Dude, @hamesetawa, you are my hero.
