### ISSUE TITLE
How to display yValues in yLabels

### ISSUE THREAD

**Issue by lamfete** [kevinzhow/PNChart#153]
Hi,

I didn't found how to display yValues in yLabels.

Can you help?

Thank you

**Comment by kevinzhow** [comment]
Which chart?

**Comment by lamfete** [comment]
@kevinzhow barchart. I want to display yValues in yLabels.

**Comment by leoreisbk** [comment]
@lamfete 

 var yLabelSectionHeight:CGFloat = (self.frame.size.height - chartMargin * 2.0 - xLabelHeight) / CGFloat(yLabels.count)
            
            for var index:Int = 0; index < yLabels.count; ++index {
                
                var labelText:String = yLabelFormatter(yLabels[index] as CGFloat) //yLabelFormatter((yValueMax * ( CGFloat(yLabels.count - index) / CGFloat(yLabels.count) ) )
                    
                    var label:PNChartLabel = PNChartLabel(frame: CGRectMake(0,yLabelSectionHeight * CGFloat(index) + chartMargin - yLabelHeight/2.0, yChartLabelWidth, yLabelHeight))
                    
                    label.font = labelFont
                    label.textColor = labelTextColor
                    label.textAlignment = NSTextAlignment.Right
                    label.text = labelText+yValueType
                    
                    labels.addObject(label)
                    self.addSubview(label)
                
            }

**Comment by lamfete** [comment]
@leoreisbk 

I already tried your code, but still have some error.
I modified a little like below

var barChart = PNBarChart(frame: CGRectMake(0, 10, 320.0, 100.0))

barChart.xLabels = ["CARBON", "KAPUR", "NAFTOMIX", "NLS", "RESIN", "SOLAR", "TITANIUM"]

barChart.yValues = [7, 5, 5, 4, 6, 2, 4]


var yLabelSectionHeight:CGFloat = (100 - barChart.chartMargin * 2.0 - barChart.xLabelHeight) / CGFloat(barChart.yLabels.count)

        for var index:Int = 0; index < barChart.yLabels.count; ++index {

            var labelText:String = barChart.yLabelFormatter(barChart.yLabels[index] as CGFloat)

            //var lb:String = barChart.yLabelFormatter((barChart.yValueMax * ( CGFloat(barChart.yLabels.count - index)

                // CGFloat(barChart.yLabels.count) )

            // yLabelFormatter((yValueMax * ( CGFloat(yLabels.count - index) / CGFloat(yLabels.count) ) )

            var label:PNChartLabel = PNChartLabel(frame: CGRectMake(0,yLabelSectionHeight * CGFloat(index) + barChart.chartMargin - barChart.yLabelHeight/2.0, barChart.yChartLabelWidth, barChart.yLabelHeight))

            label.font = barChart.labelFont

            label.textColor = barChart.labelTextColor

            label.textAlignment = NSTextAlignment.Right

            label.text = "??"

            println(labelText)

           // labels.addObject(label)

            barChart.addSubview(label)
        }

![image](https://cloud.githubusercontent.com/assets/6195369/6036714/fe0e123c-ac7b-11e4-9578-8247007df8e3.png)

**Comment by lamfete** [comment]
solved

![screen shot 2015-02-24 at 10 37 54 am](https://cloud.githubusercontent.com/assets/6195369/6342844/9aea5080-bc11-11e4-8089-3f0b235831f9.png)
