### ISSUE TITLE
Pie Chart crash when all PNPieChartDataItem value's are 0

### ISSUE THREAD

**Issue by lukegeiger** [kevinzhow/PNChart#162]
I am getting a crash when I am creating a PNPieChart with 5 PNPieChartDataItems that all have a value of 0, like so.

            NSArray *items = @[[PNPieChartDataItem dataItemWithValue:0 color:[UIColor blueColor]description:@"Desc"],
                           [PNPieChartDataItem dataItemWithValue:0 color:[UIColor greenColor] description:@"Desc"],
                           [PNPieChartDataItem dataItemWithValue:0 color:[UIColor redColor] description:@"Desc"],
                           [PNPieChartDataItem dataItemWithValue:0 color:[UIColor tealColor] description:@"Desc"],
                           [PNPieChartDataItem dataItemWithValue:0 color:[UIColor orangeColor] description:@"Desc"],
                           ];

            self.chart = [[PNPieChart alloc] initWithFrame:CGRectMake((frame.size.width-width)/2, 10, width, width) items:items];

I crash [here](https://github.com/kevinzhow/PNChart/blob/master/PNChart/PNPieChart.m#L151)

With the error:

     *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position     contains NaN: [nan nan]'
    *** First throw call stack:

**Comment by kevinzhow** [comment]
don't set it all zero @ZhangHang  any suggestion?

**Comment by lukegeiger** [comment]
@kevinzhow I am using the library to display stats on a sports team, so for example at the start of a season all players stats are 0... I am assuming thats a common use case... I came up with a workaround, on my own, but just thought I would bring it to your attention. Cool library!

**Comment by ZhangHang** [comment]
As for this kind of case , it should dividing equally. I will sent a PR if you guys agree.

**Comment by kevinzhow** [comment]
@ZhangHang yes, come on!
