### ISSUE TITLE
Cannot get PNChart to work with Swift code base with Cocoapods

### ISSUE THREAD

**Issue by scvdance** [kevinzhow/PNChart#177]
Hi,

I installed PNChart using cocoapods, and it just fails to compile.
Can anyone help me with this?

Here are some images:

![screenshot 2015-03-15 02 26 18](https://cloud.githubusercontent.com/assets/387419/6655368/00378644-cabb-11e4-8e4b-f26d26d71d13.png)
![screenshot 2015-03-15 02 26 57](https://cloud.githubusercontent.com/assets/387419/6655369/04cec208-cabb-11e4-928c-74cd47916bff.png)

**Comment by kevinzhow** [comment]
I haven't try it on Swift.
May do some discover later

**Comment by antoninbiret** [comment]
Please have a look at the pull request #178 which fix this issue
