### ISSUE TITLE
Allow rotation xLabels PNBarChart & PNLineChart

### ISSUE THREAD

**Issue by PGLongo** [kevinzhow/PNChart#181]
What do you thing to add a parameters to allow the rotation of xLabel?

```objective
#define DEGREES_TO_RADIANS(x) (M_PI * x / 180.0) 
....
label.transform= CGAffineTransformMakeRotation(DEGREES_TO_RADIANS(_rotation));
```

**Comment by kevinzhow** [comment]
I remembered there are a method to do this.

**Comment by kevinzhow** [comment]
/** Controls whether text for x-axis be straight or rotate 45 degree. */
@property (nonatomic) BOOL rotateForXAxisText;
