### ISSUE TITLE
Handle multiple chart in PNChartDelegate

### ISSUE THREAD

**Issue by PGLongo** [kevinzhow/PNChart#182]
I think that the delegate should handle multiple charts (as Objective-C usually does), actually it necessary to have multiple delegate.

``` objective
userClickedOnPieIndexItem(pieIndex: Int)
```

Should be

``` objective
userClickedOnPieChart(pieChart:PNPieChart, index: Int)
```

Do you agree?

**Comment by kevinzhow** [comment]
Yes you are right

**Comment by iosappdeveloper** [comment]
Currently, the pie Chart supports only one dimensional dataset. Any suggestion how to achieve multiple datasets? Or if you can quickly put up rough code to draw interactive graph like this...

<img width="535" alt="screen shot 2015-09-26 at 3 48 25 pm" src="https://cloud.githubusercontent.com/assets/877202/10119512/22c0b628-6466-11e5-8be4-b0056488b889.png">

Here is the jsfiddle using d3.js
http://jsfiddle.net/wuhbamnc/
