### ISSUE TITLE
PNBarchart does not fill width

### ISSUE THREAD

**Issue by aberkecz** [kevinzhow/PNChart#183]
Hi!

I'm fairly new at iOS development, so maybe I'm messing things up. My problem is that I placed a PNBarchart on a VC, it appears almost perfectly, but unfortunately it does not fill the entire width it has.
Do you have any idea how to fix this?

![Screenshot](https://cloud.githubusercontent.com/assets/6689932/6799882/d2c316e0-d219-11e4-8969-28b33add8084.png)

**Comment by kevinzhow** [comment]
ViewController has a default margins.
