### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by jmteixeira** [kevinzhow/PNChart#184]
In your project description you say that the minimum requirement is iOS 6, but when I install from CocoaPods it says:

[!] The platform of the target `Pods` (iOS 7.0) is not compatible with `PNChart (0.8.2)` which has a minimum requirement of iOS 8.0.

Can you please fix this?

Thanks,
José Teixeira

**Comment by kevinzhow** [comment]
0.8.2 drops the support of iOS6 and iOS7, you can use 0.8.1 instead

**Comment by jmteixeira** [comment]
Ok, but something is still wrong, if I do this:
```
pod 'PNChart', '~> 0.8.1'
```
It still tries to use 0.8.2, its ignoring the version.

**Comment by kevinzhow** [comment]
Seems I didn’t push the 0.8.1, try 0.8

**Comment by jmteixeira** [comment]
Sorry, same error

**Comment by kevinzhow** [comment]
remove ~> just use string ‘0.8’

**Comment by jmteixeira** [comment]
Thank you, that worked
