### ISSUE TITLE
App terminated when using bar chart

### ISSUE THREAD

**Issue by Cokile** [kevinzhow/PNChart#185]
I simply copy and paste the code in your README.md:
       `PNBarChart * barChart = [[PNBarChart alloc] initWithFrame:CGRectMake(0, 135.0, SCREEN_WIDTH, 200.0)];`
       `[barChart setXLabels:@[@"SEP 1",@"SEP 2",@"SEP 3",@"SEP 4",@"SEP 5"]];`
       `[barChart setYValues:@[@1,  @10,  @2, @6, @3]];`
       `[barChart strokeChart];`

but the app terminated:
![screen shot 2015-03-26 at 15 04 17](https://cloud.githubusercontent.com/assets/8230448/6841693/6bf82660-d3c9-11e4-9419-06ccb9852812.png)

what was wrong?

**Comment by kevinzhow** [comment]
Try the latest version
