### ISSUE TITLE
Updating of UICountingLabel library

### ISSUE THREAD

**Issue by alaaghribi** [kevinzhow/PNChart#188]
Hi,
Can you please make sure to update UICountingLabel library ? I'm already using it in my project and there is some new functions that does not exists in the current files. Or is there a way to ignore UICountingLabel files retrieving when getting it via CocoaPods ?
Thank you very much.

**Comment by kvting** [comment]
Hi,

I have the exact same request/question as @alaaghribi . I know the issue is closed but there were no follow up/comments so I'm not sure what was done (I guess the dependency was updated to the latest version at that time).

For now, I'll install manually PNChart as a workaround.

Thanks
