### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by Zyphrax** [kevinzhow/PNChart#193]
Great library that would be even greater if there was a way to turn the animations off :)

In my project the chart is updated whenever my dataset changes. The animation is nice for the initial load, but with all the updates coming in it becomes very distracting.

Could you guys add a boolean to toggle this?

**Comment by kevinzhow** [comment]
in the strokeChart method, you can add a boolean to skip all CAAnimation, i may consider to add this to PNChart in next version.
