### ISSUE TITLE
提示找不到<UICountingLabel/UICountingLabel.h>这个文件，大家有遇到过么？我是直接将PNChar文件引用到项目中的，没有用cocoapods

### ISSUE THREAD

**Issue by Z-AnDong** [kevinzhow/PNChart#195]
提示找不到<UICountingLabel/UICountingLabel.h>这个文件，大家有遇到过么？我是直接将PNChar文件引用到项目中的，没有用cocoapods

**Comment by Z-AnDong** [comment]
我的问题解决了，谢谢博主开源的框架

**Comment by fromnow** [comment]
我也遇到这个问题，请问楼主是怎么解决的？

**Comment by laihj** [comment]
找到UICountingLabel并引入工程

PNChart本身引用了UICountiingLabel，使用cocoapods的话，cocoapods自动处理了这个依整关系
不使用cocoapods，自己去引入 (UICountingLabel)[https://github.com/dataxpress/UICountingLabel]

**Comment by fromnow** [comment]
知道了，多谢
