### ISSUE TITLE
LineChart：the first point cannot be drawn at the right position due to the calculateChartPath function

### ISSUE THREAD

**Issue by fromnow** [kevinzhow/PNChart#198]
In PNLineChart.m, the innerGrade in calculateChartPath() is calculated as:
innerGrade = (yValue - _yValueMin) / (_yValueMax - _yValueMin) == 0 ? 0.5 : (yValue - _yValueMin) / (_yValueMax - _yValueMin);
How is the '0.5' defined, why？
I draw the LineChart in my project, the first point of the line cannot be drawn at the right position. If I modify the innerGrade as following:
innerGrade = (yValue - _yValueMin) / (_yValueMax - _yValueMin) 
It seems right.

**Comment by makoni** [comment]
Confirm. 

I draw a linechart with 7 values of 81. And it draws it incorrect:
![2015-05-16 18 38 57](https://cloud.githubusercontent.com/assets/234015/7666817/da95077e-fbfa-11e4-98ec-1b8c712bad68.png)

After changing in PNLineChart.m line to:
innerGrade = (yValue - _yValueMin) / (_yValueMax - _yValueMin) 

It draws correct:
![2015-05-16 18 39 59](https://cloud.githubusercontent.com/assets/234015/7666822/fb5b4de2-fbfa-11e4-96e0-f7f1ef1b1d98.png)

**Comment by ZuYuanZhou** [comment]
I find the same issue. Thanks for the fix @makoni , hope @kevinzhow fix it asap.

**Comment by kevinzhow** [comment]
the latest commit should work @ZuYuanZhou

**Comment by ZuYuanZhou** [comment]
@kevinzhow Is the Cocoapods updated? Currently I can only use pod 'PNChart', :head to get the latest version.
