### ISSUE TITLE
Problem about the min value in a lineChart

### ISSUE THREAD

**Issue by Captain116** [kevinzhow/PNChart#201]
Why the min value in a lineChart will got bigger(get  higher on Y)?
And another issue, why can't I change the color of xLabel (lineChart.xLabelColor)?
Thanks a lot.

update:

   only in this way can change xLabel's color:
    //    lineChart.xLabelColor = [UIColor whiteColor]; //color won't get changed？？？
    NSArray *arr = lineChart.xChartLabels;
    for (UILabel *label in arr) {
        label.textColor = [UIColor whiteColor];
    }

**Comment by kevinzhow** [comment]
change use lineChart.xLabelColor = [UIColor whiteColor]; before you set labels
