### ISSUE TITLE
Bar Chart not show Y Values.

### ISSUE THREAD

**Issue by nobitakun** [kevinzhow/PNChart#209]
self.barChart = [[PNBarChart alloc] initWithFrame:CGRectMake(0, 135.0, SCREEN_WIDTH, 182.0)];
        self.barChart.backgroundColor = [UIColor clearColor];
        self.barChart.yLabelFormatter = ^(CGFloat yValue){
            NSLog(@"%f", yValue);
            
            CGFloat yValueParsed = yValue;
            NSString * labelText = [NSString stringWithFormat:@"%1.f",yValueParsed];
            return labelText;
        };
        self.barChart.labelMarginTop = 5.0;
        [self.barChart setXLabels:@[@"SEP 1",@"SEP 2",@"SEP 3",@"SEP 4",@"SEP 5",@"SEP 6",@"SEP 7"]];
        self.barChart.rotateForXAxisText = true ;
      
      self.barChart.yLabelSum=5;
      self.barChart.yMaxValue=100;
      
        [self.barChart setYValues:@[@1,@24,@12,@18,@30,@10,@21]];

        self.barChart.barColorGradientStart = [UIColor blueColor];
        
        [self.barChart strokeChart];
        
        self.barChart.delegate = self;
        
        [self.view addSubview:self.barChart];

I have used that code but it not show the y Values in the chart. But in the code demo it work. what i wrong?

**Comment by kevinzhow** [comment]
check your code order
