### ISSUE TITLE
I got stuck with PNBarChart

### ISSUE THREAD

**Issue by afiq90** [kevinzhow/PNChart#213]
He there, first I wanna say thank you for the author for making this great library, It helps me a lot. But something weird happened. I tried to use barchart but my app got break at this line in PNBarChart.m, what I'm doing is i just copy PNBarChar Example code from github. I don't know how to fix this, I hope someone could help me to solve this problem. Thank you in advance.

My app got break at this line :

 NSString *labelText = _yLabelFormatter((float)_yValueMax * ( (_yLabelSum - index) / (float)_yLabelSum ));

**Comment by kevinzhow** [comment]
You can email me your example project with this issue.

**Comment by dorinsimina** [comment]
See:

barChart.yLabelFormatter = ^(CGFloat yValue){
        CGFloat yValueParsed = yValue;
        NSString * labelText = [NSString stringWithFormat:@"%0.f",yValueParsed];
        return labelText;
    };

**Comment by DaveBatton** [comment]
I hit the same thing. Same line of code. Just copied and pasted the example code from the docs into my own project, with a PNBarChart IBOutlet.
