### ISSUE TITLE
Need Help with Y-Axis scrolling

### ISSUE THREAD

**Issue by mrishi** [kevinzhow/PNChart#214]
Hello,

Many thanks for sharing this wonderful set of tools, truly professional work !!

I have set up the barchart's superview to be a scrollview to facilitate horizontal scrolling. This works but the Y-axis is scrolling along with the bars. Is there a way I can make the Y axis static, so only the bars scroll horizontally?

Also, a nice-to-have, but it would be good if the Bar Chart also has a legend view. I am currently using your delegate protocol to display the selected value only.

Cheers,
Rishi

**Comment by kevinzhow** [comment]
you can disable UIScrollView's Vertical Scroll.
StackOverflow it ;)

**Comment by mrishi** [comment]
Saw this pretty late, but thanks anyway !!
