### ISSUE TITLE
How to Add A Value for Y-Axis On Bar Chart

### ISSUE THREAD

**Issue by afiq90** [kevinzhow/PNChart#218]
How Can I Add A Value for Y-Axis On Bar Chart. Thank you.

**Comment by AmbroseSilveira** [comment]
Store the labels for y axis in yLabels array which is public variable in PNChart library and then display it according to the logic. 
1.create the interval you want to display on y axis .
2. den add label.text="interval"
3.build and run

**Comment by afiq90** [comment]
thank you.

**Comment by AmbroseSilveira** [comment]
Welcome :)
Do you know how to refresh the view for reloading PNLinechart?
