### ISSUE TITLE
CircleChart Update Issue

### ISSUE THREAD

**Issue by dbleicher** [kevinzhow/PNChart#219]
Nice library, thanks!

The default countingLabel format for CircleChart is percentage.  When you create a CircleChart and provide the current and total, the percentage is calculated and properly displayed.  If you then change the "current" number (via update or grow methods), the countingLabel adjusts to that absolute value, not to the new percentage that number represents.

In the image below, both charts were created with current/total values of 5/15 (33%).  The chart on the right was then updated (growChartByAmount: 5) to 10/15.  Note that on the right, the line length is correct (66%) but the countingLabel percentage is set to 10% (incorrect).

![circlechart](https://cloud.githubusercontent.com/assets/3764409/8169091/4279ed0a-1375-11e5-88b4-5f34ed93d9c6.png)

**Comment by kevinzhow** [comment]
use updateChartByCurrent() method

**Comment by dbleicher** [comment]
In the current version, using updateChartByCurrent() has this same problem (the grow method is just a wrapper around it).  The issue is in how the _displayCountingLabel is updated.

**Comment by dbleicher** [comment]
Basically, this issue is the same as #169, but the patch for that issue only corrected the label when it is created (not on update).  The same logic (dividing current / total) needs to be added to the updateChartByCurrent() method.
