### ISSUE TITLE
XCode 6.4中, 有个bug

### ISSUE THREAD

**Issue by ZuYuanZhou** [kevinzhow/PNChart#228]
可能是新版的编译器的问题(我用的swift),  请注意看下PNLineChart.m的第260行, 
```
for (int i = 0; i < linePointsArray.count - 1; i += 2) {
```

linePointsArray.count 是NSUInteger, 这里linePointsArray.count - 1被转成NSUInteger, 我测试图表中只有一个点的时候, 就崩溃了.

改为如下, 问题解决:
```
for (int i = 0; i < (int)linePointsArray.count - 1; i += 2) {
```

**Comment by luosam1123** [comment]
I encounter the same issue too, here is my change
for (int i = 0; i < (NSInteger)(linePointsArray.count - 1); i += 2) 
but not sure while the array linePointsArray is blank at the time.
