### ISSUE TITLE
PNBarChart yMinValue not doing what it suppose to do

### ISSUE THREAD

**Issue by Tommecpe** [kevinzhow/PNChart#236]
First, thank-you for the great work and this great library !

I'm trying to display a BarChart with a minimum value and a maximum value. My Y values are between 19 and 26, so I would like to have the YAxis starting at 19 and the biggest value at 26. Her is my code:
```
    self.barChart = [[PNBarChart alloc] initWithFrame:CGRectMake(0, 0, self.chartView.bounds.size.width, self.chartView.bounds.size.height)];
    
    self.barChart.yMaxValue = 26;
    self.barChart.yMinValue = 19;
    
    self.barChart.yLabelSuffix = @"°C";
    self.barChart.yLabelPrefix = @"";

    self.barChart.isShowNumbers = NO;
    self.barChart.showChartBorder = YES;
    
    [self.chartView addSubview:self.barChart];
    
    [self.barChart setYLabels:@[@"19", @"26"]];
    [self.barChart setYValues:@[@(19),@(20),@(21),@(22),@(23),@(24),@(25),@(26)]];
    [self.barChart setXLabels:@[@(19),@(20),@(21),@(22),@(23),@(24),@(25),@(26)]];
    [self.barChart strokeChart];
```

And here is the result

![capture d ecran 2015-07-30 a 12 06 25](https://cloud.githubusercontent.com/assets/2162676/8980787/8178a7ba-36b3-11e5-8fc9-5644eaa496c4.png)

The bars start at 0 and not at 19 ...
I look a bit in the code and I don't see how `barChart.yMinValue` is working ...

Any help ? Thanks !

**Comment by kevinzhow** [comment]
don't set setYLabels at the same time
