### ISSUE TITLE
PNChart 0.8.1 is not on CocoaPods

### ISSUE THREAD

**Issue by NoICE** [kevinzhow/PNChart#238]
Hi. Readme suggests to use PNChart 0.8.1 if a developer needs iOS 7 support, but 0.8.1 is not on cocoapods. Only 0.8 and 0.8.2. There seems to be many changes from 0.8 to 0.8.1...

**Comment by kevinzhow** [comment]
0.8.6 should support iOS 7 now

**Comment by NoICE** [comment]
Oh. I didn't see that the platform is now set to 7.0.

The readme is not very clear on that. I did a git log on the podspec and I see it now.

So I should use 0.8.1 for iOS 6, version 0.8.2 works only for iOS 8, versions 0.8.3-0.8.6 are iOS 7 compatible. Is that right? The readme should be updated to say exactly this.

Btw your master branch is stuck on 0.8.5, you have dangling tag (1 commit ahead of master)

**Comment by NoICE** [comment]
I've created new pull request for this and I'm closing this issue. Thanks
