### ISSUE TITLE
Circle chart - Shadow gradient

### ISSUE THREAD

**Issue by Kaspik** [kevinzhow/PNChart#290]
Hello,
thanks for you library!
Do you think it's possible to create circle chart with shadow gradient (and with shadow? 😄)  - not only shadow color? Something like this?

Also - is it possible to change countingLabel format? I see that this is hardcoded in "strokeChart".

Thanks!

<img width="161" alt="snimek obrazovky 2016-04-27 v 20 14 54" src="https://cloud.githubusercontent.com/assets/7204168/14863121/be546566-0cb4-11e6-91b4-30ab76878a8d.png">

**Comment by YYXuelangwang** [comment]
I think you can use a imageView under The circleChart as the shadow , after all the circleChart.backgroundColor is clearColor;

The countingLabel format, you can use UICountingLabelAttributedFormatBlock like 

    self.circleChart.countingLabel.attributedFormatBlock = ^(float value){
        NSString *text = [NSString stringWithFormat:@"%d%%",(int)value];
        NSMutableAttributedString *str = [[NSMutableAttributedString alloc] initWithString:text];
        [str addAttribute:NSForegroundColorAttributeName value:[UIColor blueColor] range:NSMakeRange(0, text.length)];
        return str;
    };
