### ISSUE TITLE
感觉给给Delegate的方法加上sender会方便一点

### ISSUE THREAD

**Issue by zoelam020** [kevinzhow/PNChart#341]
不知道是不是故意的,总之用着方便所以全部自己加上了。
@protocol PNChartDelegate <NSObject>
@optional
/**
 * Callback method that gets invoked when the user taps on the chart line.
 */
- (void)userClickedOnLinePoint:(CGPoint)point lineIndex:(NSInteger)lineIndex Sender:(id)sender;

/**
 * Callback method that gets invoked when the user taps on a chart line key point.
 */
- (void)userClickedOnLineKeyPoint:(CGPoint)point
                        lineIndex:(NSInteger)lineIndex
                       pointIndex:(NSInteger)pointIndex
                           Sender:(id)sender;

/**
 * Callback method that gets invoked when the user taps on a chart bar.
 */
- (void)userClickedOnBarAtIndex:(NSInteger)barIndex Sender:(id)sender;

- (void)userClickedOnPieIndexItem:(NSInteger)pieIndex Sender:(id)sender;
- (void)didUnselectPieItem:(id)sender;

@end

**Comment by aidongsheng** [comment]
起作用吗？

**Comment by kevinzhow** [comment]
Sender 确实有比较好
