### ISSUE TITLE
Want CircleChart with thinner line

### ISSUE THREAD

**Issue by peterlondon1** [kevinzhow/PNChart#342]
I'm trying to get a CircleChart with a thinner line.

I've tried initialising with 'overrideLineWidth' set to 5.0, but it seems to make no difference.

Any suggestions please!

(see attached for example with overrideLineWidth = 3.0
![vvv](https://cloud.githubusercontent.com/assets/312881/20804522/29eb5168-b7eb-11e6-891c-772e509ebe7f.png)

**Comment by kevinzhow** [comment]
Try https://github.com/kevinzhow/PNChart/blob/master/PNChart/PNCircleChart.m#L55
