### ISSUE TITLE
已经不再维护了？

### ISSUE THREAD

**Issue by oscams** [kevinzhow/PNChart#343]
作者貌似已经没有在维护这个项目了，大家提的issue也没有回复，个人认为bug太多，建议大家用其它的库代替，免得踩坑。。

**Comment by kevinzhow** [comment]
嗯，Chart 的需求很发散，现在确实事情太多没有时间更新了。

**Comment by sunwell** [comment]
可以考虑给别人来维护？

**Comment by kevinzhow** [comment]
@sunwell 有合适的当然可以呀
