### ISSUE TITLE
YLabels, XLabels and YValues not showing proeprly

### ISSUE THREAD

**Issue by nitin-agam** [kevinzhow/PNChart#363]
Hey there,

I'm getting this issue attached screenshot. When I'm setting YLabels and YValues both together, as I expecting the YLabels should display in left side vertically and YValues should plot the value in the graph. But no idea how you are plotting the graph. Kindly help me.

Even please see the screenshot attached here, XLabels are not showing properly.

`CGRect chartFrame = CGRectMake(10, 100, self.view.frame.size.width - 20, 300);
    
    //For BarC hart
    PNBarChart * barChart = [[PNBarChart alloc] initWithFrame:chartFrame];
    [barChart setXLabels:@[@"JAN", @"FEB", @"MAR", @"APR", @"MAY", @"JUN", @"JUL", @"AUG", @"SEP",  @"OCT", @"NOV", @"DEC"]];
    [barChart setYValues:@[@1, @10, @2, @6, @3, @1345, @10, @2, @6, @3, @34, @89]];
    [barChart setYLabels:@[@0, @100, @200, @300, @400, @500]];
    [barChart strokeChart];
    
    [self.view addSubview:barChart];`

![screen shot 2017-02-26 at 3 52 46 pm](https://cloud.githubusercontent.com/assets/12906999/23338866/aac0d47c-fc3b-11e6-86b3-10005a7e05ca.png)

**Comment by santhosh373** [comment]
same problem

**Comment by santhosh373** [comment]
this will help

[barChart setChartMarginTop:5];
