### ISSUE TITLE
给折线图设置透明度，会出现奇怪的3角型

### ISSUE THREAD

**Issue by caiZhenAn** [kevinzhow/PNChart#370]
![175892fd-599a-451d-975a-79433df2c663](https://cloud.githubusercontent.com/assets/9985131/25060329/d39d3118-21cc-11e7-839b-4c2ef0e99a41.png)

**Comment by JunyiXie** [comment]
无解 pnchart 实现方式导致的。

**Comment by kevinzhow** [comment]
很想找个时间重写一下，But 一直没有时间
你可以放进一个 ScrollView 里实现

**Comment by JunyiXie** [comment]
shouldRasterize 可以试试

**Comment by JunyiXie** [comment]
放进scrollview 滚的时候 纵坐标滚的时候会没有的
