### ISSUE TITLE
lineChart Y坐标 文字与坐标不齐、求教如何增加实心圆点类型

### ISSUE THREAD

**Issue by lvcode** [kevinzhow/PNChart#405]
虚心求教！
![image](https://user-images.githubusercontent.com/16863736/32307599-46eb6138-bf4f-11e7-9933-371fd2be0b03.png)

**Comment by JunyiXie** [comment]
https://github.com/JunyiXie/XJYChart 试试这个...

**Comment by JunyiXie** [comment]
I had Fix it .In my branch.
https://github.com/JunyiXie/PNChart

**Comment by dagundejuzi** [comment]
我找到了，设置PNLineChartData 的 data.inflexionPointWidth 属性小一点就可以。

**Comment by lvcode** [comment]
谢谢大家啦
