### ISSUE TITLE
PNLineChart 更新数据之后,原来PointLabel上的标注还存在,这个问题怎样解决呀

### ISSUE THREAD

**Issue by 1070697296** [kevinzhow/PNChart#408]

**Comment by 1070697296** [comment]
NSArray * layerArray = self.layer.sublayers;
    NSEnumerator * enumerator = [layerArray reverseObjectEnumerator];
    for (CALayer * layer in enumerator) {
        if ([layer isMemberOfClass:[CATextLayer class]]) {
            [layer removeFromSuperlayer];
        }
    }   暂时在- (void)updateChartData:(NSArray *)data中加入以上代码,问题解决了,不知道这种解决方法好不好,请指教

**Comment by kevinzhow** [comment]
嗯，works

**Comment by shineFoyMylove** [comment]
我也出现同样问题，但是不能在 updateChartData 添加代码，因为当我调用这个update方法，直接越界闪退 *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
求怎么解决
