### ISSUE TITLE
Release version 0.8.10 to CocoaPods

### ISSUE THREAD

**Issue by Kaspik** [kevinzhow/PNChart#421]
Hello Kevin!

Last version on CocoaPods is 0.8.9 from May 2016. Master is 0.8.10 with some nice features like fixes for XCode 9, UICountingLabel 1.4.1 instead of 1.0.0 etc... Could you please release this version to cocoapods? These two libraries are currently throwing a lot of warnings on XCode 9 if you use CocoaPods version.

Thanks man!

**Comment by Kaspik** [comment]
Any news @kevinzhow ? :)

**Comment by ecaselles** [comment]
@kevinzhow it would be awesome to get the latest version also published in CocoaPods. Let us know if there is anything we can do to help!

**Comment by jiaoyaxin** [comment]
复议

**Comment by jiaoyaxin** [comment]
@kevinzhow

**Comment by we7ee** [comment]
@kevinzhow Latest version is now 0.8.11 but still not on CocoaPods. Would be great to get the lates version via CocoaPods. Thank you.
