### ISSUE TITLE
How to do grouped Barchart?

### ISSUE THREAD

**Issue by mpatelCAS** [kevinzhow/PNChart#454]
Can anyone tell me how to do grouped barchart like this ?

![screen shot 2019-02-08 at 10 32 02 am](https://user-images.githubusercontent.com/11056021/52459713-d3c79900-2b8c-11e9-9db6-267dba03c486.png)

**Comment by PasqualePuzio** [comment]
@mpatelCAS Hi, did you manage to do this? If so, how? Thanks

**Comment by mpatelCAS** [comment]
@PasqualePuzio  This chart lib will not work for this I have used JS to achieve this in the application
