### ISSUE TITLE
Multi Line Chart with different number of x labels

### ISSUE THREAD

**Issue by Sun3** [kevinzhow/PNChart#73]
Is there a way to have Multiple Lines Chart where each line will have different number of x labels. Currently this causes it to crash.

For example Line 1 has 20 x labels but Line 2 has only 10 x labels points.

Any suggestions are appreciated.

**Comment by kevinzhow** [comment]
@vernon99 Yes!

**Comment by mobileSam1** [comment]
I have the same issue
please provide a solution
