### ISSUE TITLE
Error Running Code

### ISSUE THREAD

**Issue by hkfgo** [kevinzhow/PNChart#81]
I did everything as instructed(edited pod file, did pod install), but I'm getting this error running your demo code: 
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Log:

Ld /Users/henrykatz/Library/Developer/Xcode/DerivedData/PNChartDemo-hjfbbjwccfkwwngvtswkbyoqjmoi/Build/Products/Debug-iphonesimulator/PNChartDemo.app/PNChartDemo normal i386
    cd /Users/henrykatz/Downloads/PNChart-master
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk -L/Users/henrykatz/Library/Developer/Xcode/DerivedData/PNChartDemo-hjfbbjwccfkwwngvtswkbyoqjmoi/Build/Products/Debug-iphonesimulator -F/Users/henrykatz/Library/Developer/Xcode/DerivedData/PNChartDemo-hjfbbjwccfkwwngvtswkbyoqjmoi/Build/Products/Debug-iphonesimulator -filelist /Users/henrykatz/Library/Developer/Xcode/DerivedData/PNChartDemo-hjfbbjwccfkwwngvtswkbyoqjmoi/Build/Intermediates/PNChartDemo.build/Debug-iphonesimulator/PNChartDemo.build/Objects-normal/i386/PNChartDemo.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -ObjC -framework CoreGraphics -framework Foundation -framework QuartzCore -framework UIKit -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=6.0 -framework QuartzCore -framework CoreGraphics -framework UIKit -framework Foundation -lPods -Xlinker -dependency_info -Xlinker /Users/henrykatz/Library/Developer/Xcode/DerivedData/PNChartDemo-hjfbbjwccfkwwngvtswkbyoqjmoi/Build/Intermediates/PNChartDemo.build/Debug-iphonesimulator/PNChartDemo.build/Objects-normal/i386/PNChartDemo_dependency_info.dat -o /Users/henrykatz/Library/Developer/Xcode/DerivedData/PNChartDemo-hjfbbjwccfkwwngvtswkbyoqjmoi/Build/Products/Debug-iphonesimulator/PNChartDemo.app/PNChartDemo

**Comment by kevinzhow** [comment]
Please try pod way, just read the README
