### ISSUE TITLE
Is there any possibility to use PNChart with IB?

### ISSUE THREAD

**Issue by LumiaSaki** [kevinzhow/PNChart#88]
I add this amazing chart into my application through codes,and I also find that PNChart inherits from UIView,so I decide to have a try for implementing this with storyboard.I drag a UIView to my view and change the class from UIView to PNPieChart,but I find that 'items' property is 'readonly',it only can be set in initWithFrame: items: method.
Is any solution for using PNChart with storyboard or IB?Or there are some solutions already in it but I did't find them?
Thanks.

**Comment by livingspring** [comment]
if you use a xib or storyboard for this chartView, the initWithFrame will not be called ,it will replaced by initWithCoder,you can change the chart source code to support xib or storyboard.
