### ISSUE TITLE
PNLineChart 能否左右滑动？

### ISSUE THREAD

**Issue by victorjiang-zz** [kevinzhow/PNChart#93]
折线图有许多数据的时候，能否通过左右滑动来查看其他数据，而当前范围内只显示部分数据？

**Comment by bluesky0109** [comment]
放scrollview中，如果数据量大 击败上千条 如何 平滑的 高效的 过渡，会不会有性能问题？？

**Comment by kevinzhow** [comment]
担心性能问题就得重构了。。也许哪天我会做

**Comment by bluesky0109** [comment]
@kevinzhow 如果自己实现  只考虑数据量大 几百上千条的，要求可以水平滑动查看 前后数据的这种场景，尽量要 滑动 平滑过渡不卡顿 同时考虑性能，有什么具体的 实现思路 推荐吗？方便的话 烦请 给个 具体的 实现 思路步骤，使用 UIBezierPath 还是 Quartz 2D。

**Comment by laihj** [comment]
@bluesky0109 那样的话可能就不是用UIBezierPath 还是 Quartz 2D的问题了
可能得把整个chart拆开，然后利用类似UITableView的cell重用思路
